version: '3'
#DataBase
services:
  db:
    image: mysql:8.0
    container_name: mysql-Task-List
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./mysql_data:/var/lib/mysql

#phpMyAdmin




volumes:
  dbdata:
  driver: local